config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources :readers
  resources :items
  resources :carts
  resources :tags
  resources :readings
  resources :stores

  get :dashboard, to: "pages#show", id: "dashboard"
  root "pages#show", id: "landing"
end

app/models/account.rb
class Account < ActiveRecord::Base
  devise :database_authenticatable
  devise :registerable
  devise :recoverable
  devise :rememberable
  devise :validatable

  has_one :store
  has_many :carts

  validates :name, presence: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  TAX_PERCENT = 0.0

  belongs_to :account
  has_many :items

  validates :account, presence: true
  validates :tax, presence: true
  validates :total, presence: true

  monetize :total_cents

  def tax_cents
    if super then super
    else
      assign_attribute(:tax_cents, (subtotals_cents - discount_cents || 0) * TAX_PERCENT)
    end
  end

  def subtotals_cents
    items.map(&:total_cents).sum
  end

  def total_cents
    if super then super
    else
      assign_attribute(:total_cents, (subtotals_cents - discount_cents || 0) + tax_cents)
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :cart
  belongs_to :subject, polymorphic: true

  validates :cart, presence: true
  validates :subject, presence: true

  monetize :price_cents
  monetize :total_cents

  def price_cents
    if super then super
    else assign_attribute(:price_cents, (subtotals_cents - discount_cents || 0) * TAX_PERCENT)
    end
  end

  def total_cents
    if super then super
    else
      assign_attribute(:total_cents, (subtotals_cents - discount_cents || 0) * TAX_PERCENT)
    end
  end
end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :account
  belongs_to :store
  has_many :order_items

  monetize :price_cents

  validates :name, presence: true
  validates :description, presence: true
  validates :price_cents, presence: true
  validates :account, presence: true
  validates :store, presence: true
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :account
  has_many :readings

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :account, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
end

app/models/teller.rb
class Teller < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  protected def devise_parameter_sanitizer
    case
    when resource_class == Account then AccountSanitizer.new(Account, :account, params)
    else super
    end
  end

  private def after_sign_in_path_for(resource)
    request.referer || dashboard_url
  end

  private def after_sign_up_path_for(resource)
    dashboard_url
  end

  private def after_sign_out_path_for(resource)
    root_url
  end

  private def after_update_path_for(resource)
    dashboard_url
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_account!, if: :internal?

  def show
    if File.exists?(Rails.root.join("app", "views", "pages", "#{params[:id]}.html.erb"))
      render params[:id]
    else
      redirect_to "/404.html"
    end
  end

  private def internal?
    case params[:id]
    when "dashboard" then true
    else false
    end
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  before_action :authenticate_account!

  def new
    @account = current_account
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_account!

  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = current_account.build_store
  end

  def create
    @store = current_account.build_store(**StoreSanitizer.new(params))

    if @store.save!
      redirect_to store_url(@store)
    else
      render :new
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tarotsource</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_client.html.erb
<p>
  Want to purchase a reading? <%= link_to "Look through our curated tarot readers by clicking here.", stores_url %>
</p>

<p>
  <%= link_to "If you'd like to become a fortune teller, click here.", new_reader_url %>
</p>

app/views/pages/_reader.html.erb
<% if current_account.store.present? %>
  <% if current_account.readings.any? %>
    <ul>
      <% current_account.readings.each do |reading| %>
        <li><%= reading.name %></li>
      <% end %>
    </ul>
  <% else %>
  <% end %>
<% else %>
  <p>
    Would you like to sell your readings online? <%= link_to "You can create a new store with us by clicking here.", new_store_url %>
  </p>
<% end %>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>

<% if current_account.reader? %>
  <%= render partial: "reader" %>
<% else %>
  <%= render partial: "client" %>
<% end %>

app/views/pages/landing.html.erb
<h1>The Tarot Source</h1>


<% unless account_signed_in? %>
  <p>
    <%= link_to "Sign up", new_account_registration_url %>
  </p>
<% end %>

app/views/readers/new.html.erb
<h1>Apply for Reader Status</h1>

<%= form_for @account, url: registration_url(@account), html: { method: :put } do |form| %>
  <section class="field">
    <%= form.check_box :reader? %>
    <%= form.label :reader?, "I agree to the terms of service for Readers and I want to be a Reader." %>
  </section>

  <section class="field">
    <%= form.label :current_password %>
    <%= form.password_field :current_password, autocomplete: "off" %>
  </section>

  <section class="actions">
    <%= form.submit "Accept" %>
  </section>
<% end %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= form_for @store do |form| %>
  <section class="field">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true %>
  </section>

  <section class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </section>

  <section class="actions">
    <%= form.submit %>
  </section>
<% end %>

app/views/stores/show.html.erb
<% if account_signed_in? && @store.owned_by?(current_account) %>

<% end %>